<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Academy</name>
   <tag></tag>
   <elementGuidId>38303a4e-ad6b-424e-9993-3a7332f556c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='p_lt_Header']/div/div/nav/ul/li[3]/div/div/div/div/div/div[2]/div[2]/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2e89120-3166-461a-93f8-5f851d742bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-name</value>
      <webElementGuid>75a6ab63-14cd-4914-9c12-fcc77f016fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academy</value>
      <webElementGuid>0e12a8a6-b1fc-4d21-b4fa-e5f58075636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_lt_Header&quot;)/div[@class=&quot;nav-main&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;main d-flex justify-content-between align-items-center&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item dropdown show keepopen&quot;]/div[@class=&quot;dropdown-menu mega-menu mega-menu-resource show&quot;]/div[@class=&quot;dropdown-mega row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;dropdown-mega-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6 prod-col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 px-2&quot;]/a[@class=&quot;dropdown-mega-item&quot;]/span[@class=&quot;item-name&quot;]</value>
      <webElementGuid>5984cca0-e5ea-49bf-944b-fe2baaf65c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='p_lt_Header']/div/div/nav/ul/li[3]/div/div/div/div/div/div[2]/div[2]/div[2]/a/span</value>
      <webElementGuid>9dcf8790-e0c1-4350-8409-e30166883f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eBooks'])[1]/following::span[1]</value>
      <webElementGuid>01485edc-d8f1-43f6-8334-7dca43518dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webinars'])[1]/following::span[2]</value>
      <webElementGuid>478728e1-d02d-423a-8310-9e3dc4721e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::span[1]</value>
      <webElementGuid>f80d9328-ff84-4e01-b5ee-df74722846a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docs'])[1]/preceding::span[2]</value>
      <webElementGuid>525a8cc6-d643-4d33-b126-4da460644a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Academy']/parent::*</value>
      <webElementGuid>cbbc7db5-aab3-4b7f-9cdb-57209afed739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a/span</value>
      <webElementGuid>40bcc666-0ff6-425d-a348-afa9b026fe00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Academy' or . = 'Academy')]</value>
      <webElementGuid>ec2efa77-523a-4844-9385-4680e6f0a5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
