<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ReadyAPI</name>
   <tag></tag>
   <elementGuidId>f6f78b24-b48d-4337-98c1-e13bc7d2a817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='p_lt_Header']/div/div/nav/ul/li/div/div/div/div/div/div[2]/a[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16dd3379-8c5c-479b-a308-fb5ff671acaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-name</value>
      <webElementGuid>8932b368-00c4-4619-a06c-affacfee1e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ReadyAPI</value>
      <webElementGuid>5e3c6059-3ede-4238-8a32-eb614b2bb439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_lt_Header&quot;)/div[@class=&quot;nav-main&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;main d-flex justify-content-between align-items-center&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item dropdown show keepopen&quot;]/div[@class=&quot;dropdown-menu mega-menu mega-menu-products show&quot;]/div[@class=&quot;dropdown-mega row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;dropdown-mega-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-4 prod-col home pb-lg-4&quot;]/a[@class=&quot;dropdown-mega-item&quot;]/span[@class=&quot;item-name&quot;]</value>
      <webElementGuid>f1176a4b-40a1-44a5-b775-b5e21266d987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='p_lt_Header']/div/div/nav/ul/li/div/div/div/div/div/div[2]/a[2]/span[2]</value>
      <webElementGuid>3375c517-fb96-41e5-9387-a272d8fc5934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global, Synthetic API Monitoring'])[1]/following::span[2]</value>
      <webElementGuid>af8a1ddc-b040-466f-9c0a-819f6178f33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AlertSite'])[1]/following::span[3]</value>
      <webElementGuid>aa0db97e-ef32-4924-ae41-4b35b7a2183b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated API testing platform'])[1]/preceding::span[1]</value>
      <webElementGuid>711447fb-08dc-4ec2-a703-6a37caa50bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SwaggerHub'])[1]/preceding::span[3]</value>
      <webElementGuid>e97b6d64-bbeb-4e40-b2bd-733edcf45781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ReadyAPI']/parent::*</value>
      <webElementGuid>7a4d011f-744a-424c-a00b-60003ed41b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/span[2]</value>
      <webElementGuid>3fca7e73-d974-4ea4-9399-e05181c3bc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ReadyAPI' or . = 'ReadyAPI')]</value>
      <webElementGuid>f3455fe9-5510-4de6-915a-6f77f0b32725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
