<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pactflow_brand-text align-self-center h_0facf9</name>
   <tag></tag>
   <elementGuidId>ddb64ca0-481b-4093-babb-e2d0918d19cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='p_lt_Header']/div[2]/div/nav/a/img[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.brand-text.align-self-center.has-descender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d6c9abc9-f062-4750-8175-61b3430c853e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static1.smartbear.co/smartbearbrand/media/images/logos/text/ra_wordmark-clr.svg?ext=.svg</value>
      <webElementGuid>315484dc-8e78-49d5-8581-2bb9b3360157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ReadyAPI</value>
      <webElementGuid>b19b8af7-d9e5-40fb-8895-33d49f834eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>51424cb5-f45e-4d30-8d74-9ceb81177079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-text align-self-center has-descender</value>
      <webElementGuid>3aaa6760-5f1b-428a-82e7-3fe4002a5d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_lt_Header&quot;)/div[@class=&quot;nav-secondary bg-gray-xtra-light&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;secondary d-flex justify-content-between align-items-center&quot;]/a[@class=&quot;navbar-brand-product d-block&quot;]/img[@class=&quot;brand-text align-self-center has-descender&quot;]</value>
      <webElementGuid>b274a054-65e0-4857-a650-b599515b1b95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='p_lt_Header']/div[2]/div/nav/a/img[3]</value>
      <webElementGuid>99ad9e5a-f141-445b-979f-dd602607259f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ReadyAPI']</value>
      <webElementGuid>213aac46-a33b-4d66-8ee8-04f907cedeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img[3]</value>
      <webElementGuid>39fee14c-9cd5-4543-bc3c-09f6a36429a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static1.smartbear.co/smartbearbrand/media/images/logos/text/ra_wordmark-clr.svg?ext=.svg' and @alt = 'ReadyAPI']</value>
      <webElementGuid>773ad490-c35f-4ff5-9c78-9139424d407f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
